---
- name: update haitaton
  hosts: haitaton.kaupunkiymparisto.fi
  remote_user: ansible
  become: true
  tasks:
    - name: ensure docker is at the latest version
      apt:
        name: docker
        state: latest
    - name: ensure docker-compose is at the latest version
      apt:
        name: docker-compose
        state: latest
    - name: create haitaton dir
      file:
        path: /home/ansible/haitaton
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'
    - name: copy files
      copy:
        src: .
        dest: /home/ansible/haitaton
        owner: ansible
        group: ansible
        mode: '0644'
    - name: run docker-compose
      docker_compose:
        project_src: /home/ansible/haitaton
        recreate: always
        remove_images: all
        remove_orphans: yes
        remove_volumes: no
